package com.android.mySwissDorm.ui.listing

import EditListingViewModel
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.android.mySwissDorm.R
import com.android.mySwissDorm.resources.C
import com.android.mySwissDorm.ui.DefaultAddPhotoButton
import com.android.mySwissDorm.ui.DescriptionField
import com.android.mySwissDorm.ui.HousingTypeDropdown
import com.android.mySwissDorm.ui.InputSanitizers
import com.android.mySwissDorm.ui.InputSanitizers.FieldType
import com.android.mySwissDorm.ui.PriceField
import com.android.mySwissDorm.ui.ResidencyDropdownResID
import com.android.mySwissDorm.ui.RoomSizeField
import com.android.mySwissDorm.ui.TitleField
import com.android.mySwissDorm.ui.theme.MainColor
import com.android.mySwissDorm.ui.theme.TextBoxColor
import com.android.mySwissDorm.ui.theme.TextColor
import com.android.mySwissDorm.ui.utils.CustomDatePickerDialog
import com.android.mySwissDorm.ui.utils.CustomLocationDialog
import com.android.mySwissDorm.ui.utils.DateTimeUi.formatDate
import com.android.mySwissDorm.ui.utils.onUserLocationClickFunc

/**
 * Edit screen for an existing rental listing.
 *
 * Responsibilities:
 * - Loads the target listing (via [EditListingViewModel.getRentalListing]) when the composable is
 *   first composed or when [rentalListingID] changes.
 * - Displays a validated form bound to [EditListingViewModel.uiState].
 * - Exposes three navigation callbacks to the host:
 *     - [onBack]: invoked by the top-left back arrow and the "Cancel" button.
 *     - [onConfirm]: invoked after a successful save (only when the form is valid).
 *     - [onDelete]: invoked after deletion; receives the city name of the listing to let the host
 *       decide navigation.
 *
 * Notes:
 * - Input fields are normalized & validated using centralized [InputSanitizers].
 * - Error helper texts under Size/Price are shown only when the user has typed something invalid.
 *
 * @param modifier Standard Compose [Modifier].
 * @param editListingViewModel ViewModel that owns the edit state and repo calls.
 * @param onConfirm Called after a successful save of the edited listing.
 * @param onDelete Called after delete with the listing's city name (used by host for navigation).
 * @param onBack Called when user cancels or taps the back arrow.
 * @param rentalListingID The listing document id to edit; used to load data on first composition.
 *   Documentation generated by AI
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EditListingScreen(
    modifier: Modifier = Modifier,
    editListingViewModel: EditListingViewModel = viewModel(),
    onConfirm: () -> Unit,
    onDelete: (String) -> Unit,
    onBack: () -> Unit,
    rentalListingID: String
) {
  // Load listing when entering the screen or when the id changes.
  LaunchedEffect(rentalListingID) { editListingViewModel.getRentalListing(rentalListingID) }

  // Reactive UI state for the form.
  val listingUIState by editListingViewModel.uiState.collectAsState()
  val scrollState = rememberScrollState()
  var showDatePicker by remember { mutableStateOf(false) }
  val context = LocalContext.current
  val onUseCurrentLocationClick = onUserLocationClickFunc(context, editListingViewModel)

  Scaffold(
      topBar = {
        CenterAlignedTopAppBar(
            title = { Text(stringResource(R.string.edit_listing_title)) },
            navigationIcon = {
              IconButton(onClick = onBack) {
                Icon(
                    Icons.AutoMirrored.Filled.ArrowBack,
                    contentDescription = "Back",
                    tint = MainColor)
              }
            },
            actions = {
              IconButton(
                  onClick = {
                    val cityName = editListingViewModel.getCityName(listingUIState.residencyName)
                    editListingViewModel.deleteRentalListing(rentalListingID)
                    onDelete(cityName)
                  },
                  modifier = Modifier.testTag(C.EditListingScreenTags.DELETE_BUTTON)) {
                    Icon(Icons.Default.Delete, contentDescription = "Delete", tint = MainColor)
                  }
            })
      },
      bottomBar = {
        Surface(shadowElevation = 8.dp) {
          Column(Modifier.padding(16.dp), horizontalAlignment = Alignment.CenterHorizontally) {
            val ui = listingUIState
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                  Button(
                      onClick = onBack,
                      colors =
                          ButtonDefaults.buttonColors(
                              containerColor = TextBoxColor, contentColor = MainColor),
                      modifier = Modifier.weight(1f).height(52.dp),
                      shape = RoundedCornerShape(16.dp)) {
                        Text(stringResource(R.string.cancel))
                      }

                  Button(
                      onClick = {
                        if (editListingViewModel.editRentalListing(rentalListingID)) onConfirm()
                      },
                      enabled = ui.isFormValid,
                      colors =
                          ButtonDefaults.buttonColors(
                              containerColor = MainColor,
                              disabledContainerColor = MainColor.copy(alpha = 0.3f)),
                      modifier =
                          Modifier.weight(1f)
                              .height(52.dp)
                              .testTag(C.EditListingScreenTags.SAVE_BUTTON),
                      shape = RoundedCornerShape(16.dp)) {
                        Text(stringResource(R.string.save), color = Color.White)
                      }
                }
            Spacer(Modifier.height(8.dp))
            if (!ui.isFormValid) {
              Text(
                  stringResource(R.string.edit_listing_invalid_form_text),
                  style = MaterialTheme.typography.bodySmall,
                  color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
          }
        }
      }) { padding ->
        val ui = listingUIState

        val sizeInvalid =
            ui.sizeSqm.isNotBlank() &&
                !InputSanitizers.validateFinal<Double>(FieldType.RoomSize, ui.sizeSqm).isValid
        val priceInvalid =
            ui.price.isNotBlank() &&
                !InputSanitizers.validateFinal<Int>(FieldType.Price, ui.price).isValid

        Column(
            modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 16.dp, vertical = 10.dp)
                .verticalScroll(scrollState),
            verticalArrangement = Arrangement.spacedBy(14.dp)) {
              TitleField(
                  value = ui.title,
                  onValueChange = { editListingViewModel.setTitle(it) },
                  modifier = Modifier.testTag(C.EditListingScreenTags.TITLE_FIELD).fillMaxWidth())

              ResidencyDropdownResID(
                  selected = ui.residencyName,
                  onSelected = { editListingViewModel.setResidency(it) },
                  residencies = ui.residencies,
                  isListing = true,
                  accentColor = MainColor)

              HousingTypeDropdown(
                  selected = ui.housingType,
                  onSelected = { editListingViewModel.setHousingType(it) },
                  accentColor = MainColor)

              if (ui.residencyName == "Private Accommodation") {
                OutlinedButton(
                    onClick = { editListingViewModel.onCustomLocationClick(ui.customLocation) },
                    modifier =
                        Modifier.testTag(C.EditListingScreenTags.CUSTOM_LOCATION_BUTTON)
                            .fillMaxWidth()
                            .height(56.dp),
                    shape = RoundedCornerShape(16.dp),
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = TextColor)) {
                      Row(
                          modifier = Modifier.fillMaxWidth(),
                          horizontalArrangement = Arrangement.SpaceBetween,
                          verticalAlignment = Alignment.CenterVertically) {
                            Text(stringResource(R.string.location), color = TextColor)
                            Text(
                                ui.customLocation?.name
                                    ?: stringResource(R.string.add_listing_select_location),
                                color = TextColor,
                                style = MaterialTheme.typography.bodyMedium)
                          }
                    }
              }

              val sizeErrKey =
                  ui.sizeSqm
                      .takeIf { it.isNotBlank() }
                      ?.let {
                        val r = InputSanitizers.validateFinal<Double>(FieldType.RoomSize, it)
                        if (r.isValid) null else r.errorKey
                      }

              val priceErrKey =
                  ui.price
                      .takeIf { it.isNotBlank() }
                      ?.let {
                        val r = InputSanitizers.validateFinal<Int>(FieldType.Price, it)
                        if (r.isValid) null else r.errorKey
                      }

              RoomSizeField(
                  value = ui.sizeSqm,
                  onValueChange = { editListingViewModel.setSizeSqm(it) },
                  externalErrorKey = sizeErrKey,
                  modifier = Modifier.testTag(C.EditListingScreenTags.SIZE_FIELD).fillMaxWidth())

              if (sizeInvalid) {
                Text(
                    text = stringResource(R.string.edit_listing_invalid_size_text),
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall)
              }

              PriceField(
                  value = ui.price,
                  onValueChange = { editListingViewModel.setPrice(it) },
                  externalErrorKey = priceErrKey,
                  modifier = Modifier.testTag(C.EditListingScreenTags.PRICE_FIELD).fillMaxWidth())

              if (priceInvalid) {
                Text(
                    text = stringResource(R.string.edit_listing_invalid_price_text),
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall)
              }

              // Start Date Field
              OutlinedButton(
                  onClick = { showDatePicker = true },
                  modifier =
                      Modifier.testTag(C.EditListingScreenTags.START_DATE_FIELD)
                          .fillMaxWidth()
                          .height(56.dp),
                  shape = RoundedCornerShape(16.dp),
                  colors = ButtonDefaults.outlinedButtonColors(contentColor = TextColor)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically) {
                          Text(stringResource(R.string.start_date), color = TextColor)
                          Text(
                              formatDate(ui.startDate),
                              color = TextColor,
                              style = MaterialTheme.typography.bodyMedium)
                        }
                  }

              DescriptionField(
                  value = ui.description,
                  onValueChange = { editListingViewModel.setDescription(it) },
                  maxLines = 6,
                  modifier = Modifier.testTag(C.EditListingScreenTags.DESC_FIELD).fillMaxWidth())

              Text(stringResource(R.string.photos), style = MaterialTheme.typography.titleMedium)
              Row(
                  verticalAlignment = Alignment.CenterVertically,
                  horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    DefaultAddPhotoButton(onSelectPhoto = {}) // TODO display the photo
              }
            }

        // Date Picker Dialog
        CustomDatePickerDialog(
            showDialog = showDatePicker,
            initialDate = ui.startDate,
            onDismiss = { showDatePicker = false },
            onDateSelected = { timestamp -> editListingViewModel.setStartDate(timestamp) })

        // Custom Location Dialog
        if (ui.showCustomLocationDialog) {
          val onValueChange =
              remember<(String) -> Unit> {
                { query -> editListingViewModel.setCustomLocationQuery(query) }
              }
          val onDropDownLocationSelect =
              remember<(com.android.mySwissDorm.model.map.Location) -> Unit> {
                { location -> editListingViewModel.setCustomLocation(location) }
              }
          val onDismiss = remember { { editListingViewModel.dismissCustomLocationDialog() } }
          val onConfirm =
              remember<(com.android.mySwissDorm.model.map.Location) -> Unit> {
                { location ->
                  editListingViewModel.setCustomLocation(location)
                  editListingViewModel.dismissCustomLocationDialog()
                }
              }

          CustomLocationDialog(
              value = ui.customLocationQuery,
              currentLocation = ui.customLocation,
              locationSuggestions = ui.locationSuggestions,
              onValueChange = onValueChange,
              onDropDownLocationSelect = onDropDownLocationSelect,
              onDismiss = onDismiss,
              onConfirm = onConfirm,
              onUseCurrentLocationClick = onUseCurrentLocationClick)
        }
      }
}
