package com.android.mySwissDorm.end2end

import android.content.Context
import android.location.Location
import android.location.LocationManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.isDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performScrollTo
import androidx.compose.ui.test.performTextInput
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.android.mySwissDorm.MySwissDormApp
import com.android.mySwissDorm.model.authentification.AuthRepositoryFirebase
import com.android.mySwissDorm.model.authentification.AuthRepositoryProvider
import com.android.mySwissDorm.model.city.CitiesRepositoryFirestore
import com.android.mySwissDorm.model.city.CitiesRepositoryProvider
import com.android.mySwissDorm.model.profile.ProfileRepositoryFirestore
import com.android.mySwissDorm.model.profile.ProfileRepositoryProvider
import com.android.mySwissDorm.model.rental.RentalListingRepositoryFirestore
import com.android.mySwissDorm.model.rental.RentalListingRepositoryProvider
import com.android.mySwissDorm.model.residency.ResidenciesRepositoryFirestore
import com.android.mySwissDorm.model.residency.ResidenciesRepositoryProvider
import com.android.mySwissDorm.model.review.ReviewsRepositoryFirestore
import com.android.mySwissDorm.model.review.ReviewsRepositoryProvider
import com.android.mySwissDorm.resources.C
import com.android.mySwissDorm.screen.SignInScreen
import com.android.mySwissDorm.screen.SignUpScreen
import com.android.mySwissDorm.ui.homepage.HomePageScreenTestTags
import com.android.mySwissDorm.utils.FakeCredentialManager
import com.android.mySwissDorm.utils.FakeJwtGenerator
import com.android.mySwissDorm.utils.FakeUser
import com.android.mySwissDorm.utils.FirebaseEmulator
import com.android.mySwissDorm.utils.FirestoreTest
import io.github.kakaocup.compose.node.element.ComposeScreen
import kotlin.time.DurationUnit
import kotlin.time.toDuration
import kotlinx.coroutines.test.runTest
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class Epic2Test : FirestoreTest() {

  private lateinit var ownerId: String
  private lateinit var otherId: String

  val locationManager = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager

  override fun createRepositories() {
    AuthRepositoryProvider.repository = AuthRepositoryFirebase(FirebaseEmulator.auth)
    CitiesRepositoryProvider.repository = CitiesRepositoryFirestore(FirebaseEmulator.firestore)
    ProfileRepositoryProvider.repository = ProfileRepositoryFirestore(FirebaseEmulator.firestore)
    RentalListingRepositoryProvider.repository =
        RentalListingRepositoryFirestore(FirebaseEmulator.firestore)
    ResidenciesRepositoryProvider.repository =
        ResidenciesRepositoryFirestore(FirebaseEmulator.firestore)
    ReviewsRepositoryProvider.repository = ReviewsRepositoryFirestore(FirebaseEmulator.firestore)

    runTest {
      switchToUser(FakeUser.FakeUser2)
      otherId =
          FirebaseEmulator.auth.currentUser?.uid ?: throw NullPointerException("No user logged in")
      ProfileRepositoryProvider.repository.createProfile(profile2.copy(ownerId = otherId))

      residencies.forEach { ResidenciesRepositoryProvider.repository.addResidency(it) }
      cities.forEach { CitiesRepositoryProvider.repository.addCity(it) }

      rentalListing1 = rentalListing1.copy(ownerId = otherId)
      RentalListingRepositoryProvider.repository.addRentalListing(rentalListing1)

      reviewVortex1 = reviewVortex1.copy(ownerId = otherId)
      ReviewsRepositoryProvider.repository.addReview(reviewVortex1)

      switchToUser(FakeUser.FakeUser1)
      ownerId =
          FirebaseEmulator.auth.currentUser?.uid ?: throw NullPointerException("No user logged in")
    }
    FirebaseEmulator.auth.signOut()
  }

  @get:Rule val compose = createComposeRule()

  @Before
  override fun setUp() {
    super.setUp()
    FirebaseEmulator.auth.signOut()
    setMockLocation(46.5197, 6.6323) // Lausanne
  }

  // Function generated by an AI
  private fun setMockLocation(lat: Double, lon: Double) {
    val context = ApplicationProvider.getApplicationContext<Context>()
    val locationManager = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager

    val provider = LocationManager.GPS_PROVIDER

    try {
      locationManager.addTestProvider(provider, false, false, false, false, true, true, true, 0, 5)
    } catch (_: IllegalArgumentException) {}

    locationManager.setTestProviderEnabled(provider, true)

    val location =
        Location(provider).apply {
          latitude = lat
          longitude = lon
          accuracy = 1f
          time = System.currentTimeMillis()
        }

    locationManager.setTestProviderLocation(provider, location)
  }

  /**
   * The test does the following actions :
   * 1. Sign Up
   * 2. Select current location
   * 3. Add a new RentalListing
   * 4. Block a user
   * 5. Add a new Review
   * 6. Edit the new Review
   */
  @Test
  fun epicTest2() {
    runTest(timeout = 60.toDuration(unit = DurationUnit.SECONDS)) {
      val fakePhoneNumber = "774321122"
      val fakeLastName = "Doe"
      val fakeGoogleIdToken =
          FakeJwtGenerator.createFakeGoogleIdToken(
              FakeUser.FakeUser1.userName, email = FakeUser.FakeUser1.email)
      val fakeCredentialManager = FakeCredentialManager.create(fakeGoogleIdToken)

      compose.setContent { MySwissDormApp(LocalContext.current, fakeCredentialManager) }

      // 1. Sign up
      ComposeScreen.onComposeScreen<SignInScreen>(compose) {
        assertIsDisplayed()
        signUpButton {
          assertIsDisplayed()
          performClick()
        }
      }
      compose.waitForIdle()

      // Fill the profile form and register
      ComposeScreen.onComposeScreen<SignUpScreen>(compose) {
        assertIsDisplayed()
        signUpNameField {
          assertIsDisplayed()
          performTextInput(FakeUser.FakeUser1.userName)
        }
        signUpLastNameField {
          assertIsDisplayed()
          performTextInput(fakeLastName)
        }
        signUpPhoneNumberField {
          assertIsDisplayed()
          performTextInput(fakePhoneNumber)
        }
        signUpButton {
          assertIsDisplayed()
          performScrollTo()
          assertIsEnabled()
          performClick()
        }
      }

      compose.waitForIdle()

      // 2. Select current location
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(HomePageScreenTestTags.LOCATION_SELECTION).isDisplayed()
      }
      compose
          .onNodeWithTag(HomePageScreenTestTags.getTestTagForCityCard("Lausanne"))
          .performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(HomePageScreenTestTags.getTestTagForCityCard("Lausanne"))
          .assertIsDisplayed()
          .performClick()

      compose.waitForIdle()

      // 3. Add a RentalListing
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.BrowseCityTags.FABSCRIM, useUnmergedTree = true).isDisplayed()
      }
      compose
          .onNodeWithTag(C.BrowseCityTags.FABSCRIM, useUnmergedTree = true)
          .assertIsDisplayed()
          .performClick()

      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.BrowseCityTags.FABMENULISTING).isDisplayed()
      }
      compose.onNodeWithTag(C.BrowseCityTags.FABMENULISTING).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // on AddListingScreen :
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.AddListingScreenTags.TITLE_FIELD).isDisplayed()
      }
      compose
          .onNodeWithTag(C.AddListingScreenTags.TITLE_FIELD)
          .assertIsDisplayed()
          .performTextInput("My first listing")

      compose
          .onNodeWithTag(C.SanitizedResidencyDropdownTags.RESIDENCY_DROPDOWN_BOX)
          .assertIsDisplayed()
          .performClick()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.SanitizedResidencyDropdownTags.getResidencyTag(vortex.name))
          .assertIsDisplayed()
          .performClick()

      compose.onNodeWithTag(C.AddListingScreenTags.SIZE_FIELD).performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.AddListingScreenTags.SIZE_FIELD)
          .assertIsDisplayed()
          .performTextInput("44")

      compose.onNodeWithTag(C.AddListingScreenTags.PRICE_FIELD).performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.AddListingScreenTags.PRICE_FIELD)
          .assertIsDisplayed()
          .performTextInput("4400")

      compose.onNodeWithTag(C.AddListingScreenTags.DESC_FIELD).performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.AddListingScreenTags.DESC_FIELD)
          .assertIsDisplayed()
          .performTextInput("Simple description")

      compose
          .onNodeWithTag(C.AddListingScreenTags.CONFIRM_BUTTON)
          .assertIsDisplayed()
          .performClick()

      compose.waitForIdle()

      // 4. Block a user

      // On the ViewListingScreen
      compose.waitUntil(5_000) { compose.onNodeWithTag(C.ViewListingTags.TITLE).isDisplayed() }

      compose.onNodeWithTag(C.ViewListingTags.BACK_BTN).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // On BrowseCityScreen
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.BrowseCityTags.LISTING_LIST).isDisplayed() &&
            compose.onNodeWithText(rentalListing1.title, useUnmergedTree = true).isDisplayed()
      }

      compose
          .onNodeWithText(rentalListing1.title, useUnmergedTree = true)
          .assertIsDisplayed()
          .performClick()

      compose.waitForIdle()

      // On ViewListingScreen
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.ViewListingTags.TITLE).isDisplayed() &&
            compose.onNodeWithTag(C.ViewListingTags.POSTED_BY).isDisplayed()
      }

      compose.onNodeWithTag(C.ViewListingTags.POSTED_BY).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // On ViewProfileScreen
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.ViewUserProfileTags.BLOCK_BUTTON).isDisplayed()
      }

      compose.onNodeWithTag(C.ViewUserProfileTags.BLOCK_BUTTON).assertIsDisplayed().performClick()

      compose.waitForIdle()

      compose.onNodeWithTag(C.ViewUserProfileTags.BACK_BTN).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // 5. Add a Review

      // On ViewListingScreen
      compose.waitUntil(5_000) { compose.onNodeWithTag(C.ViewListingTags.BACK_BTN).isDisplayed() }
      compose.onNodeWithTag(C.ViewListingTags.BACK_BTN).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // On BrowseCityScreen
      compose.waitUntil(5_000) { compose.onNodeWithTag(C.BrowseCityTags.FABSCRIM).isDisplayed() }
      compose.onNodeWithTag(C.BrowseCityTags.FABSCRIM).assertIsDisplayed().performClick()

      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.BrowseCityTags.FABMENUREVIEW).isDisplayed()
      }
      compose.onNodeWithTag(C.BrowseCityTags.FABMENUREVIEW).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // On AddReviewScreen
      compose.waitUntil(5_000) { compose.onNodeWithTag(C.AddReviewTags.TITLE_FIELD).isDisplayed() }
      compose
          .onNodeWithTag(C.AddReviewTags.TITLE_FIELD)
          .assertIsDisplayed()
          .performTextInput("My first review")

      compose
          .onNodeWithTag(C.SanitizedResidencyDropdownTags.RESIDENCY_DROPDOWN_BOX)
          .assertIsDisplayed()
          .performClick()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.SanitizedResidencyDropdownTags.getResidencyTag(vortex.name))
          .assertIsDisplayed()
          .performClick()

      compose.onNodeWithTag(C.AddReviewTags.SIZE_FIELD).performScrollTo()
      compose.waitForIdle()
      compose.onNodeWithTag(C.AddReviewTags.SIZE_FIELD).assertIsDisplayed().performTextInput("44")

      compose.onNodeWithTag(C.AddReviewTags.PRICE_FIELD).performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.AddReviewTags.PRICE_FIELD)
          .assertIsDisplayed()
          .performTextInput("4400")

      compose.onNodeWithTag(C.AddReviewTags.DESC_FIELD).performScrollTo()
      compose.waitForIdle()
      compose
          .onNodeWithTag(C.AddReviewTags.DESC_FIELD)
          .assertIsDisplayed()
          .performTextInput("Simple description")

      compose.onNodeWithTag(C.StarRatingBarTags.getStarTag(4)).performScrollTo()
      compose.waitForIdle()
      compose.onNodeWithTag(C.StarRatingBarTags.getStarTag(4)).assertIsDisplayed().performClick()

      compose.onNodeWithTag(C.AddReviewTags.SUBMIT_BUTTON).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // 6. Edit a Review

      // On ViewReviewScreen
      compose.waitUntil(5_000) { compose.onNodeWithTag(C.ViewReviewTags.TITLE).isDisplayed() }

      compose.onNodeWithTag(C.ViewReviewTags.EDIT_BTN).performScrollTo()
      compose.waitForIdle()
      compose.onNodeWithTag(C.ViewReviewTags.EDIT_BTN).assertIsDisplayed().performClick()

      compose.waitForIdle()

      // On EditReviewScreen
      compose.waitUntil(5_000) {
        compose.onNodeWithTag(C.EditReviewTags.REVIEW_TITLE).isDisplayed()
      }
      compose
          .onNodeWithTag(C.EditReviewTags.REVIEW_TITLE)
          .assertIsDisplayed()
          .performTextInput("Much better title")

      compose.onNodeWithTag(C.EditReviewTags.SAVE_BUTTON).assertIsDisplayed().performClick()

      compose.waitForIdle()
    }
  }
}
